"use client";

import "./globals.css";
import "./layout.css";

import { Inter } from "next/font/google";
import Navbar from "./navbar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [sidebar, SetSidebar] = useState(true);
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="applayout_container">
          <div
            className="applayout_sidebar_container"
            style={{
              width: sidebar ? "20%" : "0%",
              display: !sidebar ? "none" : "block",
            }}
          >
            <p
              onClick={() => {
                SetSidebar(false);
              }}
            >
              sidebar
            </p>
          </div>
          <div
            className="applayout_hori_container"
            style={{ width: sidebar ? "80%" : "100%" }}
          >
            <div className="app_navbar_container">
              <Navbar />
            </div>
            <div className="applayout_children_container">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
